# Generated by Django 5.2.8 on 2025-12-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique coupon code (stored in uppercase)', max_length=50, unique=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, help_text='Flat discount amount', max_digits=10)),
                ('min_order_amount', models.DecimalField(decimal_places=2, help_text='Minimum order amount required to apply this coupon', max_digits=10)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('usage_limit', models.PositiveIntegerField(help_text='Maximum number of times this coupon can be used')),
                ('used_count', models.PositiveIntegerField(default=0, help_text='Number of times this coupon has been used')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
