# Generated by Django 5.2.8 on 2026-01-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_coupon_max_uses_per_user_couponusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupon_source',
            field=models.CharField(choices=[('normal', 'Normal'), ('referral', 'Referral')], default='normal', max_length=20),
        ),
    ]
