# Generated by Django 5.2.8 on 2025-12-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoffer',
            name='min_order_price',
            field=models.PositiveIntegerField(default=1000, help_text='Minimum product price to apply this offer'),
        ),
    ]
