# Generated by Django 5.2.8 on 2025-12-18 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_productoffer_min_order_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productoffer',
            old_name='min_order_price',
            new_name='min_product_price',
        ),
    ]
