# Generated by Django 5.2.8 on 2025-12-18 10:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_rename_min_order_price_productoffer_min_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoffer',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
