# Generated by Django 5.2.8 on 2025-12-18 10:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_productoffer_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoffer',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
