# Generated by Django 5.2.8 on 2025-12-20 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_alter_productoffer_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoffer',
            name='max_product_price',
            field=models.PositiveIntegerField(default=10000, help_text='Maximum product price to apply this offer'),
            preserve_default=False,
        ),
    ]
