# Generated by Django 5.2.8 on 2026-01-23 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_categoryoffer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoffer',
            name='max_product_price',
        ),
        migrations.RemoveField(
            model_name='productoffer',
            name='min_product_price',
        ),
    ]
