# Generated by Django 5.2.8 on 2026-01-10 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_orderitem_net_paid_amount'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='order_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='orders.orderitem'),
        ),
    ]
