# Generated by Django 5.2.8 on 2025-11-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='joined_date',
            field=models.DateField(auto_now=True),
        ),
    ]
