# Generated by Django 5.2.8 on 2025-11-21 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_customuser_joined_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='joined_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
