# Generated by Django 5.2.8 on 2025-12-14 12:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0006_address_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
