# Generated by Django 5.2.8 on 2026-01-08 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0008_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone_number',
            field=models.CharField(max_length=30),
        ),
    ]
