# Generated by Django 5.2.8 on 2025-12-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitems_tax_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=10),
            preserve_default=False,
        ),
    ]
