# Generated by Django 5.2.8 on 2025-12-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cartitems_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
