# Generated by Django 5.2.8 on 2025-12-08 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_sub_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='sub_order_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
