# Generated by Django 5.2.8 on 2025-12-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
