# Generated by Django 5.2.8 on 2025-12-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_order_razorpay_order_id_order_razorpay_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='net_paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Actual amount paid for this item after coupon', max_digits=10),
            preserve_default=False,
        ),
    ]
