# Generated by Django 5.2.8 on 2025-11-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='joined_date',
            field=models.DateField(auto_now=True),
        ),
    ]
