# Generated by Django 5.2.8 on 2025-11-19 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_joined_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='joined_date',
        ),
    ]
