# Generated by Django 5.2.8 on 2025-11-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_productimage_variant_productimage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariants',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
