# Generated by Django 5.2.8 on 2025-12-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productvariants_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariants',
            name='gst_rate',
            field=models.FloatField(default=18.0),
        ),
    ]
