# Generated by Django 5.2.8 on 2025-12-12 04:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_productvariants_gst_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
