# Generated by Django 5.2.8 on 2025-12-12 04:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_products_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
