# Generated by Django 5.2.8 on 2025-12-12 12:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_products_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariants',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
