# Generated by Django 5.2.8 on 2025-12-12 12:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_productvariants_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariants',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
